### ISSUE TITLE
Change the command prefix on help commands

### ISSUE THREAD

**Issue by NeoMahler** [CatIRCBots/Granota#27]
When the command prefix is not the default (.), help.py still says that you have to write .commands instead of ,commands

**Comment by jeda** [comment]
Done. I've fixed this. Now it should say the prefix.

**Comment by NeoMahler** [comment]
@JeDa , no, it does not work yet:

> [16:26:48] -NeoMahler- ,help
> [16:26:49] -Granota- NeoMahler: Write .help <command> (for example .help c) to get help about a   command, or .commands to get a list of commands.

I changed temporary the prefix from "." to ","

**Comment by NeoMahler** [comment]
Update: it works with mikicatbot:

> [16:58:15] -mikicat- .help
> [16:58:16] -Granota- mikicat: Write .help <command> (for example .help c) to get help about a command, or .commands to get a list of commands.
> [16:58:16] -Mikicatbot- mikicat: Escriu .ajuda <ordre> (per exemple .help c) per obtindre ajuda per una ordre, o .ordres per una llista d'ordres

probably I have to restart Granota. Anyway, it says the configuration variable "prefix", and because it is a regexp it can say things like .

**Comment by NeoMahler** [comment]
fixed!
