### ISSUE TITLE
Bug in partido.py

### ISSUE THREAD

**Issue by NeoMahler** [CatIRCBots/Granota#28]
There are different errors in this module. Here is the log:

> [20:32:49] -mikicat- %partit CUP
> [20:32:50] -Mikicatbot- KeyError: 'P102' (source unknown)
> [20:33:05] -mikicat- %partido
> [20:33:05] -Mikicatbot- AttributeError: 'NoneType' object has no attribute 'decode' (source unknown)

**Comment by ElGatoSaez** [comment]
P102 = No political party found

NoneType error = no string to search

These errors just need a friendly error message

**Comment by mikicat** [comment]
ok

**Comment by mikicat** [comment]
I think I've solved it.

**Comment by NeoMahler** [comment]
Yes, now it doesn't rise errors, but I think there's still a problem; the bot is always saying "This political party has not been found". Could it be a Wikidata API problem? I will check it later.

**Comment by ElGatoSaez** [comment]
Take in care that this module doesn't show info from political parties, it shows the political affiliation of a person. Can I have some examples, please? 

Enviado desde mi iPad

**Comment by jeda** [comment]
There's things I've saw.

<&JeDa> .partido Nicolás Maduro
<%Granota> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 5: ordinal not in range(128) (file "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode)
<&JeDa> .partido Nicolas Maduro
<%Granota> IndexError: list index out of range (file "/home/ubuntu/workspace/Granota/willie/modules/partido.py", line 19, in partido)
<&JeDa> .partido A non-existent guy
<%Granota> IndexError: list index out of range (file "/home/ubuntu/workspace/Granota/willie/modules/partido.py", line 19, in partido)

**Comment by jeda** [comment]
Also this:

<&JeDa> .partido Barack Obama
<%Granota> This political party has not been found
<&JeDa> .partido Obama
<%Granota> This political party has not been found

**Comment by mikicat** [comment]
If the module searches people, and not political parties, should we change the module name (and error messages)?

**Comment by NeoMahler** [comment]
@mikicat: yes, but first we should fix that bug :stuck_out_tongue_winking_eye:

**Comment by ElGatoSaez** [comment]
Module don't search for people, searches for the political afiliation of a
person.

2015-09-28 18:04 GMT-03:00 Miquel Comas notifications@github.com:

> If the module searches people, and not political parties, should we change
> the module name (and error messages)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CatIRCBots/Granota/issues/28#issuecomment-143873469.

## 

_Saludos Coordiales_
_Sebastián Sáez M._

**Comment by ElGatoSaez** [comment]
Line 19 error is because parameter that you searched isn't a person or
doesn't exists on Wikidata, the error from <%Granota> This political party
has not been found" it's from a KeyError, bot console has all KeyError
parameters and details, if we have them we can solve it.

2015-09-29 16:34 GMT-03:00 Sebastián Ignacio Sáez Moscoso <
geniointernet@gmail.com>:

> Module don't search for people, searches for the political afiliation of a
> person.
> 
> 2015-09-28 18:04 GMT-03:00 Miquel Comas notifications@github.com:
> 
> > If the module searches people, and not political parties, should we
> > change the module name (and error messages)?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CatIRCBots/Granota/issues/28#issuecomment-143873469.
> 
> ## 
> 
> _Saludos Coordiales_
> _Sebastián Sáez M._

## 

_Saludos Coordiales_
_Sebastián Sáez M._

**Comment by NeoMahler** [comment]
@ElGatoSaez here you have the exceptions:
- -NeoMahler- .partido Obama

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/ubuntu/workspace/Granota/willie/modules/partido.py", line 43, in partido
    linkWikipediaPartido = tododelPartido['entities'][numerobuscaPartido]['labels']['en']['value']
KeyError: 'en'
```
- -NeoMahler- .partido Rajoy

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/ubuntu/workspace/Granota/willie/modules/partido.py", line 19, in partido
    idWikidata = todo["search"][0]["id"]
IndexError: list index out of range
```

I have removed temporary the "This political party has not been found" to see exactly the problems. Thanks for your help!

**Comment by NeoMahler** [comment]
It works now, I restored the friendly error message.
