### ISSUE TITLE
Confusion between command in the help system

### ISSUE THREAD

**Issue by NeoMahler** [CatIRCBots/Granota#33]
Log:

~ 20:13:12 ~ -@NeoMahler- ,ayuda diec
~ 20:13:13 ~ -@Granota- diec: Da un link hacia el DIEC (diccionario catalán) para la palabra especificada. | Example: ,diec àdhuc | Alias (or in other languages): diec
~ 20:13:17 ~ -@NeoMahler- ,ayuda raiseException
~ 20:13:17 ~ -@Granota- diec: Da un link hacia el DIEC (diccionario catalán) para la palabra especificada. | Example: ,diec àdhuc | Alias (or in other languages): diec

It seems that only happens with the raiseExceptions command.

**Comment by NeoMahler** [comment]
It seems it happens with all inputs that doesn't exist _and_ raiseException (for some reason, the bot thinks that it doesn't exist).

**Comment by NeoMahler** [comment]
raiseexception issue resolved; But there's still the non-existent commands problem

**Comment by ElGatoSaez** [comment]
Solving it mate

**Comment by ElGatoSaez** [comment]
Need admin permissions to reload and update the bot when I push

**Comment by jeda** [comment]
I would reload it for you.

**Comment by ElGatoSaez** [comment]
No thanks. I blocked you anyways here on GitHub. I'll wait NeoMahler better.

**Comment by jeda** [comment]
> block

I will act as I didn't read that stupidity...

**Comment by NeoMahler** [comment]
Make the pull request, and I will review it and update the bot when I
connect.

**Comment by ElGatoSaez** [comment]
Thanks <<<33333333♡♡♡♡♡♡♡♡♡♡♡<<<33333333333♡♡♡♡

**Comment by jeda** [comment]
Meh, I fixed this.
