### ISSUE TITLE
Granota ping timeouts when files get deleted

### ISSUE THREAD

**Issue by jeda** [CatIRCBots/Granota#35]
I've noticed that if Granota files are deleted, it ping timeouts.

**Comment by NeoMahler** [comment]
@JeDa Well, it's normal... what it shouldn't disconnect if you delete its files?

**Comment by jeda** [comment]
I think instead of simply disconnecting by ping timeout, it should do something, as raise an error (and say it on a quit) or something.

**Comment by NeoMahler** [comment]
The problem is that making the bot disconnect with a custom quitmsg we have to add it somewhere in granota's folder; and if it is deleted it will not work.

**Comment by NeoMahler** [comment]
Testing comment. I will remove it.

**Comment by NeoMahler** [comment]
@JeDa will you make something about this (Read my last comment)?

**Comment by jeda** [comment]
I dude.

**Comment by NeoMahler** [comment]
Ok, closing the issue. If you decide to try to solve it, make a pull request or commit the changes directly.
