### ISSUE TITLE
Test script not working on Jenkins

### ISSUE THREAD

**Issue by jeda** [CatIRCBots/Granota#36]
I dude why it doesn't works, but the problem is on the test file. We should check.

**Comment by NeoMahler** [comment]
Do you mean tesbot.py?

**Comment by NeoMahler** [comment]
Ah, I have the error (maybe) coveralls doesn't work with Jenkins by default, so I will have to add the repo token.

**Comment by NeoMahler** [comment]
@JeDa It seems Jenkins doesn't work; travis ci is making the tests, but the last jenkins test happened more than 12 hours ago. Is there any way to manually run the test?

**Comment by jeda** [comment]
Jenkins automatically builds on every commit.

**Comment by jeda** [comment]
You can manually run it but you should have a shell on endofworld.jedayoshi.me

**Comment by JeDa** [comment]
test

**Comment by NeoMahler** [comment]
Maybe it was a problem of my internet connection. Now, the Jenkins CI is building... I think it's taking too long?

**Comment by jeda** [comment]
I was reinstalling Jenkins CI, that's why it said it was building.

No worries, I've fixed this.
