### ISSUE TITLE
google search is broken

### ISSUE THREAD

**Issue by NeoMahler** [CatIRCBots/Granota#49]
I think that Google API has changed something and now google search function doesn't work.

**Comment by mikicat** [comment]
It must have changed, as Searcher does not query to google too

**Comment by NeoMahler** [comment]
Half-fixed. Google search works, but google count still fails.

**Comment by NeoMahler** [comment]
I commented out google count functions, as the new library doesn't support this function. Also, adapted the .search command to work with the new google function.
